"use client";

import { useEffect, useState } from "react";

import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

import { Sparkles, TrendingUp } from "lucide-react";

import CheckoutButton from "./CheckoutButton";
import { getCheckoutRecommendation } from "@/lib/checkout-api";

interface Recommendation {
  id: string;
  title: string;
  explanation: string;
  expected_revenue: number;
  confidence: number;
}

export default function AIUpsellCard() {
  const [recommendation, setRecommendation] = useState<Recommendation | null>(
    null,
  );

  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function load() {
      try {
        const data = await getCheckoutRecommendation();
        setRecommendation(data);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    }

    load();
  }, []);

  if (loading) {
    return <Card className="p-6">Loading AI recommendation...</Card>;
  }

  if (!recommendation) {
    return <Card className="p-6">No recommendation available.</Card>;
  }

  return (
    <Card className="space-y-6 border-primary p-6">
      {/* Header */}

      <div className="flex items-center gap-3">
        <div className="rounded-lg bg-primary/10 p-2">
          <Sparkles className="h-6 w-6 text-primary" />
        </div>

        <div>
          <h2 className="text-xl font-semibold">AI Checkout Recommendation</h2>

          <p className="text-sm text-muted-foreground">
            Generated by MerchantOS AI
          </p>
        </div>
      </div>

      {/* Recommendation */}

      <div className="rounded-lg bg-muted/40 p-4">
        <p className="font-medium">{recommendation.title}</p>
      </div>

      {/* Stats */}

      <div className="grid grid-cols-2 gap-4">
        <div className="rounded-lg border p-4">
          <p className="text-sm text-muted-foreground">Expected Revenue</p>

          <div className="mt-2 flex items-center gap-2">
            <TrendingUp className="h-5 w-5 text-green-600" />

            <span className="text-2xl font-bold">
              ₹{recommendation.expected_revenue.toLocaleString()}
            </span>
          </div>
        </div>

        <div className="rounded-lg border p-4">
          <p className="text-sm text-muted-foreground">Confidence</p>

          <div className="mt-2">
            <Badge className="text-base">{recommendation.confidence}%</Badge>
          </div>
        </div>
      </div>

      {/* Explanation */}

      <div className="rounded-lg border-l-4 border-primary bg-primary/5 p-4">
        <p className="text-sm font-semibold">Why this recommendation?</p>

        <p className="mt-2 text-sm text-muted-foreground">
          {recommendation.explanation}
        </p>
      </div>

      {/* Payment */}

      <CheckoutButton amount={499} recommendationId={recommendation.id} />
    </Card>
  );
}
