"use client";

import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Sparkles, TrendingUp } from "lucide-react";

import CheckoutButton from "./CheckoutButton";

export default function AIUpsellCard() {
  return (
    <Card className="space-y-6 border-primary p-6">

      {/* Header */}

      <div className="flex items-center gap-3">

        <div className="rounded-lg bg-primary/10 p-2">
          <Sparkles className="h-6 w-6 text-primary" />
        </div>

        <div>

          <h2 className="text-xl font-semibold">
            AI Checkout Recommendation
          </h2>

          <p className="text-sm text-muted-foreground">
            Generated by MerchantOS AI
          </p>

        </div>

      </div>

      {/* Recommendation */}

      <div className="rounded-lg bg-muted/40 p-4">

        <p className="font-medium">
          Customers purchasing
          <span className="font-bold text-primary">
            {" "}Running Shoes{" "}
          </span>
          frequently add
          <span className="font-bold text-primary">
            Shoe Care Kit
          </span>
          during checkout.
        </p>

      </div>

      {/* Stats */}

      <div className="grid grid-cols-2 gap-4">

        <div className="rounded-lg border p-4">

          <p className="text-sm text-muted-foreground">
            Expected Revenue
          </p>

          <div className="mt-2 flex items-center gap-2">

            <TrendingUp className="h-5 w-5 text-green-600" />

            <span className="text-2xl font-bold">
              ₹12,000
            </span>

          </div>

        </div>

        <div className="rounded-lg border p-4">

          <p className="text-sm text-muted-foreground">
            Confidence
          </p>

          <div className="mt-2">

            <Badge className="text-base">
              93%
            </Badge>

          </div>

        </div>

      </div>

      {/* Explanation */}

      <div className="rounded-lg border-l-4 border-primary bg-primary/5 p-4">

        <p className="text-sm">
          <strong>Why this recommendation?</strong>
        </p>

        <p className="mt-2 text-sm text-muted-foreground">
          Based on recent customer purchase patterns,
          enabling this AI upsell can increase average
          order value and improve checkout conversion.
        </p>

      </div>

      {/* Razorpay Payment */}

      <CheckoutButton
        amount={499}
        recommendationId="demo-recommendation-id"
      />

    </Card>
  );
}