"""create campaigns table

Revision ID: cf41b7ab35a9
Revises: b82d6d180569
Create Date: 2026-08-25 19:55:46.144921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf41b7ab35a9'
down_revision: Union[str, None] = 'b82d6d180569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=120), nullable=False),
    sa.Column('discount_percentage', sa.Integer(), nullable=False),
    sa.Column('expected_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaigns')
    # ### end Alembic commands ###
