from random import choice, randint

from sqlalchemy.orm import Session

from app.models.campaign import Campaign


TITLES = [
    "Weekend Mega Sale",
    "Diwali Bonanza",
    "Summer Fitness Drive",
    "Back to Gym Offer",
    "Running Festival",
    "Cricket Season Sale",
    "Buy More Save More",
    "Premium Sports Collection",
]

AUDIENCES = [
    "New Customers",
    "Existing Customers",
    "VIP Customers",
    "Fitness Enthusiasts",
    "All Customers",
]

STATUS = [
    "Draft",
    "Running",
    "Completed",
]


def seed_campaigns(
    db: Session,
    merchant_id,
    count: int = 10,
):

    existing = (
        db.query(Campaign)
        .filter(
            Campaign.merchant_id == merchant_id
        )
        .count()
    )

    if existing >= count:
        print("✓ Campaigns already seeded")
        return

    campaigns = []

    for title in TITLES[:count]:

        campaign = Campaign(
            merchant_id=merchant_id,
            title=title,
            description=f"{title} campaign generated by MerchantOS AI.",
            audience=choice(AUDIENCES),
            discount_percentage=randint(5, 40),
            expected_revenue=randint(
                10000,
                300000,
            ),
            confidence=randint(
                75,
                99,
            ),
            status=choice(STATUS),
            requires_approval=choice(
                [
                    True,
                    False,
                ]
            ),
        )

        campaigns.append(
            campaign
        )

    db.add_all(campaigns)
    db.commit()

    print(f"✓ Seeded {len(campaigns)} campaigns")